### PR TITLE
test fail

### PR DESCRIPTION
**Pull request by SiebelsTim**

### CODE REVIEW

**Comment by SiebelsTim** [comment]
testing travis.

**Comment by SiebelsTim** [comment]
Looks like travis doesn't work yet. In my fork it works however (https://travis-ci.org/SiebelsTim/asmcupruntime). Have you set up everything correctly? You might still need to activate it in https://travis-ci.org/profile

**Comment by SiebelsTim** [comment]
This wasn't supposed to be merged :D. I wanted to test travisci.

**Comment by krisives** [comment]
I also needed a way to make Travis see a push so I made double use of this =)

**Comment by krisives** [comment]
Github was down yesterday and some of the buttons I needed to press to
allow TravisCI didnt seem to be working. I will try hooking it up today
again.

**Pull request merged**
