### PR TITLE
Fixed accelerometer returning unintended data...

### LINKED ISSUE #80: Accelerometer Question
I wrote a simple program to sample and test values from the built in Accelerometer (as the documentation is sparse on it)

```
c_0f
push8 #IO_MOTOR
io
c_0f
push8 #IO_STEER
io
push8 #IO_ACCELEROMETER
io
loop:
nop
jmp loop
```

This should set the bot to a dead standstill, but when I read the two float on the stack I get 

0x47c61b9b for Y
0x47fdd4a8 for X

My assumption is that these should read zero, correct? My assumption is that this might be a mis-read if I'm polling the Accelerometer too soon after setting the motor/steer. Because if I poll IO_ACCELEROMETER again immediately after the first poll, it'll return all zeroes. 

```
c_0f
push8 #IO_MOTOR
io
c_0f
push8 #IO_STEER
io
push8 #IO_ACCELEROMETER
io
push8 #IO_ACCELEROMETER
io
loop:
nop
jmp loop
```

In this case, the stack reads (reading forward)
0x00000000
0x00000000
0x47c61b9b
0x47fdd4a8

### PR DESCRIPTION
**Pull request by MLanghof**
...on first use.
Fixes #80.

### CODE REVIEW

**Comment by SiebelsTim** [comment]
@MLanghof couldn't you correctly set up lastX and lastY to be the roboter's position? That way we don't introduce a new variable and the first read of the accelerometer will return real data, opposed to 0.

Imagine my roboter is running for a while. The first call to IO_ACCELEROMETER happenes. My roboter might have traveled a long distance, but the first call to IO_ACCELEROMETER will always be 0.

**Comment by krisives** [comment]
I think that `Robot.position()` should simply set `lastX` and `lastY` since that's the method used to "teleport robots" outside of the game conditions.

@MLanghof Thank you for helping with this. Think you can implement it by patching `position()`?

Thanks @SiebelsTim for giving his opinion too.

**Comment by MLanghof** [comment]
Oh right, I suppose there is an initial position to initialize them with. Should that be updated when the bot is teleported?

**Review by SiebelsTim — COMMENTED** [review]
This is a great candidate for a test so we don't do this mistake again :)

**Comment by krisives** [comment]
Any ideas on how we can make a good test for this?

**Comment by MLanghof** [comment]
Yeah I was just wondering the same thing. This particular IO command might be doable, but especially things like IO_SENSOR sound painful to produce test cases for.

**Pull request merged**
